[manager]
prepend_keymap = [

{ on =  "<Enter>", run = "enter", desc = "enter dir without opening text editor" },

{ on = ["p"],       run = "plugin smart-paste",   desc = "Paste into the hovered directory or CWD" },
{ on = [ "g", "d" ],       run = "cd ~/Downloads",   desc = "Go ~/Downloads" },
{ on = [ "g", "p" ],       run = "cd ~/Projects",   desc = "Go ~/Projects" },
{ on = [ "g", "c" ],       run = "cd ~/dotfiles",   desc = "Go ~/Config" },
{ on = [ "M" ],       run = "plugin mount",   desc = "mount plugin" },
{ on = [ "g", "r" ],       run = 'shell -- ya emit cd "$(git rev-parse --show-topjevel)"'},
{ on   = [ "S" ], run  = "plugin what-size", desc = "Calc size of selection or cwd" },
 ]


append_keymap = [
	# ...
{ on =  "<Enter>", run = "enter", desc = "enter dir without opening text editor" },
]

# [[manager.prepend_keymap]]
# on = "<Enter>"
# run = "enter"
#
# [[manager.prepend_keymap]]
# on  = "M"
# run = "plugin mount"
#
# [[manager.prepend_keymap]]
# on  = "y"
# run = [ 'shell -- echo "$@" | xclip -i -selection clipboard -t text/uri-list', "yank" ]
#
