[flavor]
# dark = "dracula"
# dark = "catppuccin-mocha"
# dark = "everforest-medium"
# dark = "monokai-vibrant"
# dark = "onedark"
# dark = "sunset"
# dark = "ayu-dark"
dark = "timu-macos-dark"
# light = "timu-macos-light"
# dark = "flexoki-dark"
# dark = "ashen"
