[mgr]
show_hidden = true

[opener]
app_image = [
  { run = '"$1"', orphan = true, desc = "Run AppImage", for = "unix" },
]
pdff = [{ run = 'zathura "$@"', desc = "zathura", block = true, for = "unix" }]


[open]
prepend_rules = [
  { name = "*.AppImage", use = [
    "app_image",
  ] },
  { mime = "application/pdf", use = [
    "pdff",
    "reveal",
  ] },
]


[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

# [plugin]
# prepend_preloaders = [
#   # Image
#   { mime = "image/{avif,hei?,jxl}", run = "echo" },
#   { mime = "image/svg+xml", run = "echo" },
#   { mime = "image/*", run = "echo" },
#   # Video
#   { mime = "video/*", run = "video" },
#   # PDF
#   { mime = "application/pdf", run = "pdf" },
#   # Font
#   { mime = "font/*", run = "font" },
#   { mime = "application/ms-opentype", run = "font" },
# ]
# prepend_previewers = [
#   { name = "*/", run = "folder" },
#   # Code
#   { mime = "text/*", run = "code" },
#   { mime = "application/{mbox,javascript,wine-extension-ini}", run = "code" },
#   # JSON
#   { mime = "application/{json,ndjson}", run = "json" },
#   # Image
#   { mime = "image/{avif,hei?,jxl}", run = "echo" },
#   { mime = "image/svg+xml", run = "echo" },
#   { mime = "image/*", run = "echo" },
#   # Video
#   { mime = "video/*", run = "video" },
#   # PDF
#   { mime = "application/pdf", run = "pdf" },
#   # Archive
#   { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", run = "archive" },
#   { mime = "application/{debian*-package,redhat-package-manager,rpm,android.package-archive}", run = "archive" },
#   { name = "*.{AppImage,appimage}", run = "archive" },
#   # Virtual Disk / Disk Image
#   { mime = "application/{iso9660-image,qemu-disk,ms-wim,apple-diskimage}", run = "archive" },
#   { mime = "application/virtualbox-{vhd,vhdx}", run = "archive" },
#   { name = "*.{img,fat,ext,ext2,ext3,ext4,squashfs,ntfs,hfs,hfsx}", run = "archive" },
#   # Font
#   { mime = "font/*", run = "font" },
#   { mime = "application/ms-opentype", run = "font" },
#   # Empty file
#   { mime = "inode/empty", run = "empty" },
#   # Fallback
#   { name = "*", run = "file" },
# ]
